name: Keep Streamlit App Alive

# Trigger this workflow on a schedule — here, every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit app
        run: |
          curl -fsS https://scharf-finance-app.streamlit.app/ || exit 1
